/**
 * Contract data for the skills-sync checker (`scripts/check-skills-sync.ts`).
 * One place to update when the sync contract between the two managed skill
 * trees (`.claude/skills` ↔ `.agents/skills`) changes: after a `10x get`
 * moves an adaptation site, after a new local extension is added, or when a
 * new per-tool adaptation is introduced. Deliberately plain data — easy to
 * swap wholesale once m5l4 ("Shared AI Registry") delivers stronger
 * sentinel-marker / manifest-tracked patterns.
 */

export interface AdaptedLinePair {
  /** Exact full line content in the `.claude` copy. */
  claude: string;
  /** Exact full line content in the `.agents` copy. */
  agents: string;
}

export interface SentinelFile {
  /** Path relative to each skills tree (posix separators). */
  path: string;
  /** Exact substrings that must be present in the file in BOTH trees. */
  sentinels: string[];
}

export interface SkillsSyncConfig {
  /** Repo-relative path of the Claude Code skills tree (the `10x get` target). */
  claudeSkillsDir: string;
  /** Repo-relative path of the Codex-adapted skills tree. */
  agentsSkillsDir: string;
  /** Repo-relative path of the 10x-cli manifest (the sha256 baseline of the last `10x get`). */
  manifestPath: string;
  /** Repo-relative path of the manifest-tracked prompts directory (`.claude` only — no `.agents` twin). */
  claudePromptsDir: string;
  /** Skills present in the trees that come from the starter bootstrap (`skills-lock.json`), not the manifest. */
  lockBootstrapSkills: string[];
  /**
   * Manifest-tracked files with INVERTED hash semantics: they carry local
   * extensions, so a manifest MISMATCH is the healthy state and a MATCH means
   * a `10x get` wiped the extension (the `755065a` incident).
   */
  extendedSkills: SentinelFile[];
  /** Hand-maintained files inside managed skill dirs: tree parity + sentinels required, no manifest baseline. */
  manualParityFiles: SentinelFile[];
  /**
   * Per-file allowlist of deliberate per-tool adaptations. Keyed by
   * tree-relative path; every entry is an exact 1:1 line substitution
   * (`.claude` line ↔ `.agents` line). Any other pair difference — or an
   * expected substitution that is no longer present — is drift.
   */
  adaptedLines: Record<string, AdaptedLinePair[]>;
  /**
   * Known local deviations from the manifest baseline, pinned by sha256 of
   * the CURRENT on-disk bytes. Keyed by repo-relative path. A normal managed
   * file is OK when its hash matches the manifest OR its pinned value here;
   * anything else is drift. Extended skills ignore this map (their healthy
   * state is any-mismatch + sentinels).
   */
  acceptedLocalHashes: Record<string, string>;
}

export const EXTENDED_SKILLS: SentinelFile[] = [
  {
    path: "10x-archive/SKILL.md",
    sentinels: [
      "**Sync downstream trackers**",
      "`## Backlog Handoff`",
      "context/foundation/github-issues.md",
      "## Status updates",
      'gh issue close <n> --comment "Archived',
    ],
  },
  {
    path: "10x-impl-review/SKILL.md",
    // Deliberately avoids the `CLAUDE.md`/`AGENTS.md` fragment of the
    // mutation-check paragraph — that token is per-tool adapted between trees.
    sentinels: [
      "### Mutation check (conditional — risk-critical modules only)",
      "npx stryker run --mutate",
      "test-plan.md §4",
    ],
  },
];

export const MANUAL_PARITY_FILES: SentinelFile[] = [
  {
    path: "10x-impl-review/SKILL.user.md",
    sentinels: [
      "### Mutation check (conditional — risk-critical modules only)",
      "npx stryker run --mutate",
      "test-plan.md §4",
    ],
  },
];

/**
 * Generated by line-diffing the 9 adapted file pairs after the Phase-1
 * re-sync (20 substitutions). Do not hand-edit line content — regenerate by
 * comparing the pair line-by-line after any deliberate adaptation change.
 */
export const ADAPTED_LINES: Record<string, AdaptedLinePair[]> = {
  "10x-agents-md/SKILL.md": [
    {
      claude:
        "- **Discover locally first.** Inspect the files actually living next to the target: sibling source files, the nearest `index.*`/`mod.rs`/`__init__.py`, co-located tests, the parent directory's README if any, and any nested config (e.g. `tsconfig.json`, `.eslintrc`, route manifests) that overrides repo-level defaults. Only consult repo-root docs (`README.md`, `CLAUDE.md`) to **resolve conflicts** or pull a single canonical `@`-reference — not as the primary source.",
      agents:
        "- **Discover locally first.** Inspect the files actually living next to the target: sibling source files, the nearest `index.*`/`mod.rs`/`__init__.py`, co-located tests, the parent directory's README if any, and any nested config (e.g. `tsconfig.json`, `.eslintrc`, route manifests) that overrides repo-level defaults. Only consult repo-root docs (`README.md`, `AGENTS.md`) to **resolve conflicts** or pull a single canonical `@`-reference — not as the primary source.",
    },
    {
      claude:
        '  - *Tripwires* — directory-specific "never do X" rules visible in siblings or a nearby CLAUDE.md fragment.',
      agents:
        '  - *Tripwires* — directory-specific "never do X" rules visible in siblings or a nearby AGENTS.md fragment.',
    },
    {
      claude: "- Claude Code → `AskUserQuestion`",
      agents: "- Codex → `AskUserQuestion`",
    },
    {
      claude: "- Claude Code → `Agent` (with `Explore`/`general-purpose` subagent types)",
      agents: "- Codex → `Agent` (with `Explore`/`general-purpose` subagent types)",
    },
    {
      claude: '   - Any hard "never do X" rule visible in CLAUDE.md, README, or CI validators.',
      agents: '   - Any hard "never do X" rule visible in AGENTS.md, README, or CI validators.',
    },
    {
      claude:
        "   - `git diff --stat LAST_TOUCH..HEAD -- README.md CLAUDE.md docs/` — has top-level documentation moved or changed?",
      agents:
        "   - `git diff --stat LAST_TOUCH..HEAD -- README.md AGENTS.md docs/` — has top-level documentation moved or changed?",
    },
    {
      claude:
        "   - **REMOVE** — the underlying file/command/convention no longer exists, or the rule has been contradicted by a newer source (CLAUDE.md, README) that you trust more.",
      agents:
        "   - **REMOVE** — the underlying file/command/convention no longer exists, or the rule has been contradicted by a newer source (AGENTS.md, README) that you trust more.",
    },
  ],
  "10x-e2e/SKILL.md": [
    {
      claude:
        "   - **E2E rules**: the rules file the agent reads automatically before generating code (`CLAUDE.md`, `.cursor/rules/`, or a dedicated file in the test dir). If absent, create it from `references/e2e-quality-rules.md`.",
      agents:
        "   - **E2E rules**: the rules file the agent reads automatically before generating code (`AGENTS.md`, `.cursor/rules/`, or a dedicated file in the test dir). If absent, create it from `references/e2e-quality-rules.md`.",
    },
  ],
  "10x-e2e/references/e2e-quality-rules.md": [
    {
      claude: "generating code (`CLAUDE.md`, `.cursor/rules/`, or a dedicated file in the test",
      agents: "generating code (`AGENTS.md`, `.cursor/rules/`, or a dedicated file in the test",
    },
  ],
  "10x-impl-review/SKILL.md": [
    {
      claude:
        "Run this **only** when a file under review is a risk area in `context/foundation/test-plan.md §4` (e.g. `src/lib/services/photo-job.service.ts`). If the reviewed change touches no §4 risk area, **skip entirely** — mutation testing is a targeted gate, not a default pass, and is **never** run in CI (see `CLAUDE.md` → _Mutation testing_).",
      agents:
        "Run this **only** when a file under review is a risk area in `context/foundation/test-plan.md §4` (e.g. `src/lib/services/photo-job.service.ts`). If the reviewed change touches no §4 risk area, **skip entirely** — mutation testing is a targeted gate, not a default pass, and is **never** run in CI (see `AGENTS.md` → _Mutation testing_).",
    },
  ],
  "10x-impl-review/SKILL.user.md": [
    {
      claude:
        "Run this **only** when a file under review is a risk area in `context/foundation/test-plan.md §4` (e.g. `src/lib/services/photo-job.service.ts`). If the reviewed change touches no §4 risk area, **skip entirely** — mutation testing is a targeted gate, not a default pass, and is **never** run in CI (see `CLAUDE.md` → _Mutation testing_).",
      agents:
        "Run this **only** when a file under review is a risk area in `context/foundation/test-plan.md §4` (e.g. `src/lib/services/photo-job.service.ts`). If the reviewed change touches no §4 risk area, **skip entirely** — mutation testing is a targeted gate, not a default pass, and is **never** run in CI (see `AGENTS.md` → _Mutation testing_).",
    },
  ],
  "10x-infra-research/SKILL.md": [
    {
      claude: "7. MCP server or Claude/AI agent integration (if any)",
      agents: "7. MCP server or Codex/AI agent integration (if any)",
    },
  ],
  "10x-roadmap/SKILL.md": [
    {
      claude: "- Claude Code → `AskUserQuestion`",
      agents: "- Codex → `AskUserQuestion`",
    },
    {
      claude: "- Claude Code → `Agent` with an Explore/general-purpose subagent type",
      agents: "- Codex → `Agent` with an Explore/general-purpose subagent type",
    },
  ],
  "10x-rule-review/SKILL.md": [
    {
      claude: "- `@CLAUDE.md`",
      agents: "- `@AGENTS.md`",
    },
    {
      claude: "- `~/.claude/CLAUDE.md`",
      agents: "- `~/.codex/AGENTS.md`",
    },
  ],
  "10x-stack-assess/SKILL.md": [
    {
      claude:
        '- Add explicit type annotations convention to CLAUDE.md ("All new code must include type annotations at function boundaries")',
      agents:
        '- Add explicit type annotations convention to AGENTS.md ("All new code must include type annotations at function boundaries")',
    },
    {
      claude:
        '- Document folder structure conventions in CLAUDE.md ("Routes live in src/routes/, middleware in src/middleware/, ...")',
      agents:
        '- Document folder structure conventions in AGENTS.md ("Routes live in src/routes/, middleware in src/middleware/, ...")',
    },
    {
      claude: "- Add framework-specific idiom examples to CLAUDE.md",
      agents: "- Add framework-specific idiom examples to AGENTS.md",
    },
    {
      claude:
        '4. **Compensation is concrete, not generic.** Every compensation entry must be a ready-to-paste instruction file rule. "Add better documentation" is not compensation; "Add to CLAUDE.md: `## Routing — Routes are registered in src/routes/index.ts. Each route file exports a default Hono handler. Middleware runs in registration order.`" is compensation.',
      agents:
        '4. **Compensation is concrete, not generic.** Every compensation entry must be a ready-to-paste instruction file rule. "Add better documentation" is not compensation; "Add to AGENTS.md: `## Routing — Routes are registered in src/routes/index.ts. Each route file exports a default Hono handler. Middleware runs in registration order.`" is compensation.',
    },
  ],
};

/**
 * Formatter-noise baseline (2026-07-18): these 8 files were reformatted by
 * lint-staged's `prettier --write` at their very first commit (m3l4 initial,
 * m5l1 initial, PR #85 — all before `.prettierignore` landed in a8782f4), so
 * their pristine upstream bytes never existed in git and the manifest hash
 * can never match. Semantically zero drift. Pinned to the exact formatted
 * bytes: any FUTURE edit still alarms. After the next `10x get` restores
 * upstream bytes these entries go inert and can be dropped.
 */
export const ACCEPTED_LOCAL_HASHES: Record<string, string> = {
  ".claude/skills/10x-e2e/SKILL.md": "548aea02f324130ba461a6a0660669baca541768b8dc17789c4b848f16d75bf7",
  ".claude/skills/10x-e2e/references/browser-driven-generation.md":
    "826b011c2e4edb133c9ba2ec1aa1220216979dd3aa41f1f61e4af5047acbadf4",
  ".claude/skills/10x-e2e/references/e2e-anti-patterns.md":
    "92a48588e6c3a9465e36f60cdc17e67e52a1432f29a28288ef91413ff0f52eb1",
  ".claude/skills/10x-e2e/references/e2e-prompt-template.md":
    "626c66ac597b4954f493e6be1150e2351752d6960aac4d197718b303620266af",
  ".claude/skills/10x-e2e/references/e2e-quality-rules.md":
    "f42546fd1cc6395e4274b86ace96a30589dfd35f19378a496806f2ecf1effdb2",
  ".claude/skills/10x-e2e/references/seed-test-pattern.md":
    "a70fd860c53eda1e1251472a90a25c32084b2aba0c62736ae348ed4b332a249d",
  ".claude/skills/10x-opportunity-map/SKILL.md": "bc24fdf565c9b7fb928bdaaa6537368975ae3c4e535c0c86837117d7e8d313e9",
  ".claude/prompts/mvp-check.md": "5674efc9b394335ea09fc480ebde58eab8a67418c3da4eeb86f077e1665bbab9",
};

export const SKILLS_SYNC_CONFIG: SkillsSyncConfig = {
  claudeSkillsDir: ".claude/skills",
  agentsSkillsDir: ".agents/skills",
  manifestPath: ".claude/.10x-cli-manifest.json",
  claudePromptsDir: ".claude/prompts",
  lockBootstrapSkills: ["10x-cli-guide", "10x-cli-setup"],
  extendedSkills: EXTENDED_SKILLS,
  manualParityFiles: MANUAL_PARITY_FILES,
  adaptedLines: ADAPTED_LINES,
  acceptedLocalHashes: ACCEPTED_LOCAL_HASHES,
};
